name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. v1.4.0)"
        required: true
      prerelease:
        description: "Mark as prerelease?"
        required: false
        type: boolean
        default: false
      notes:
        description: "Release notes / description"
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.2.0

      - name: Install Rust
        uses: MatteoH2O1999/setup-rust@v2.1.1

      - name: Lint with ruff
        run: uvx ruff check src/omni_script/

      - name: Test with pytest
        run: uv run pytest

      - name: Build
        run: uv run build.py

      - name: Copy build artifact per OS (Windows)
        if: ${{ runner.os == 'Windows'}}
        run: |
          cp dist\omni.exe omni-windows.exe
          cp dist\vm.exe omvm-windows.exe

      - name: Copy build artifact per OS (Linux)
        if: ${{ runner.os == 'Linux'}}
        run: |
          cp dist/omni omni-linux
          cp dist/vm omvm-linux

      - name: Copy build artifact per OS (macOS)
        if: ${{ runner.os == 'macOS'}}
        run: |
          cp dist/omni omni-macos
          cp dist/vm omvm-macos


      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: omni-${{ runner.os }}
          path: |
            ./omni-*.exe
            ./omni-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        run: |
          git tag "${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Download matrix artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.notes }}
          prerelease: ${{ inputs.prerelease }}
          files: release-artifacts/**/* 
